### ISSUE TITLE
TE Display issue

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [aldenbe/Eve_Industry_Calculator#13]
The Max TE will only display as 10, even though the maximum is 20
![capture3](https://user-images.githubusercontent.com/31759736/38959654-4db73d02-4316-11e8-85b6-6766312b7b30.PNG)

unlike with the ME, 1 research run for TE gives a 2% bonus, so the maximum TE is 20. I don't know if there are any errors with the calculations or just the display.

**Comment by aldenbe** [comment]
I don't actually use TE, so I used https://support.eveonline.com/hc/en-us/articles/203210512-Time-Efficiency-Research as my reference which states that each run grants a 2% reduction. The input assumes the user will input the number of TE runs done. For each input run time will be reduced by 2%. If this presentation is different from in game, let me know and I will adjust it.

**Comment by ALongStringOfNumbers** [comment]
Using the number of TE runs done also works, I was just slightly confused as the normal form that I see research displayed in is as percentages, such as 10/20, instead of seeing it as number of runs done, 10/10.

**Comment by aldenbe** [comment]
Changed to reflect in game display as opposed to my misinterpretation of how it worked, as suggested by ALongStringOfNumbers. TE max is now 20 and calculations have been adjusted to use given number as percent reduction instead of counting as TE run and giving 2%.
